server:
    address: 192.168.2.222
    port: 9999

logging:
    file:
        devilyu.log
    level:
        mybatis: DEBUG
        spring: DEBUG
        muyu: DEBUG

spring:
    datasource:

        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: xmgl
        password: js1

        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource

        filters: stat
        maxActive: 100
        initialSize: 10
        maxWait: 100
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20

    ## Redis 配置
    ## Redis数据库索引（默认为0）
    session:
        store-type: redis
        cache-seconds: 100
        cookie:
              name: MUYU-SESSIONID
    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 100
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
    messages:
        basename: messages

management:
    security:
        enabled: false

prefixPath: /api

