server:
    address: localhost
    port: 9999

logging:
    file:
        devilyu.log
    level:
        mybatis: DEBUG
        spring: DEBUG
        muyu: DEBUG

spring:
    http:
        multipart:
            enabled:  true
            maxFileSize: 10Mb
            maxRequestSize: 10Mb

    datasource:

        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@localhost:1521:orcl
        username: muyu
        password: muyu
        DataSchema: muyu
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource

        filters: stat
        maxActive: 100
        initialSize: 10
        maxWait: 100
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    activiti:
      checkProcessDefinitions:  false

    redis:
        database: 0
        host: 127.0.0.1
        port: 6379
        timeout: 100
        pool:
            max-active: 8
            max-wait: -1
            max-idle: 8
            min-idle: 0
    messages:
        basename: messages

    jackson:
        default-property-inclusion: non_null
        date-format: yyyy-MM-dd HH:mm:ss

    session:
      store-type: redis
      timeout:  900  #15分钟超时
    mvc:
      date-format: yyyy-MM-dd HH:mm:ss
      view:
        suffix: .html
        prefix: static

management:
    security:
        enabled: false
#
prefixPath: /api

#分页参数
pageSize  : 50

#Tree 参数
rootId :  0

#文件上传路径
filePath: E:\\files\
